### ISSUE TITLE
How to train with own dataset?

### ISSUE THREAD

**Issue by Heidisnaps** [dshahrokhian/YOLO_tensorflow#6]
Hi.everyone.

I want to use this code to do yolo training.
What do I need to train my own dataset? (ex. xxx.weight, xxxx.ckpt ..etc...)
And what code should I run?

Thanks:)

**Comment by dshahrokhian** [comment]
Hello,

The easiest solution is to structure your dataset similarly to VOC, and then change [this line](https://github.com/dshahrokhian/YOLO_tensorflow/blob/master/data_parsing/voc_utils.py#L11) to reference to your own dataset directory.

Being honest, if I was you I would use [this repo](https://github.com/thtrieu/darkflow) instead. It is much better, since ours is already outdated.

Dan

**Comment by StefaniaTp** [comment]
@Heidisnaps did you solve this problem? I want to try this network with my own weights and dataset, but I don't know how to do this
